mybatis:
    configuration:
        aggressive-lazy-loading: true
    mapper-locations: classpath*:/sqlMapper/*Mapper.xml
server:
    port: 7769
    context-path: /auth-server
    use-forward-headers: false
    tomcat:
       uri-encoding: UTF-8

spring:
    aop:
        proxy-target-class: true
    master-datasource:
        name: master
        url: jdbc:mysql://localhost:3306/myFrameAdmin?characterEncoding=UTF-8
        username: root
        password: 3245
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 10
        maxActive: 20
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 10
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select 'x'
    read-datasource:
        name: read
        url: jdbc:mysql://localhost:3306/myFrameAdmin?characterEncoding=UTF-8
        username: root
        password: 3245
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 10
        maxActive: 20
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 10
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select 'x'
    redis:
        database: 0
        pool:
          max-active: 100
          max-idle: 30
          max-wait: -1
          min-idle: 80
        timeout: 30000
        redis-sensors:
          host: localhost
          port: 6379
          password:
          testOnBorrow: false
        redis-app:
          host: localhost
          port: 6379
          password:
          testOnBorrow: false